config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'main/index'

  namespace :category do
    post 'ajax_add_category'
    post 'ajax_edit_category'
    post 'ajax_delete_category'
  end

  namespace :money_operation do
    get 'export'
    get 'income_chart'
    get 'expenses_chart'
    post 'render_main_table'
    post 'render_add_modal'
    post 'render_edit_modal'
    post 'render_chart_modal'
    post 'ajax_add_money_operation'
    post 'ajax_edit_money_operation'
    post 'ajax_delete_money_operation'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @money_operations = MoneyOperation::Finder.new(current_user, params).find
    @income_categories = Category::Finder.new(current_user, CategoryType.find_by(name: 'Income')).find
    @expenses_categories = Category::Finder.new(current_user, CategoryType.find_by(name: 'Expenses')).find
  end
end

app/views/main/_about_section.html.erb
<!-- About Section -->
<section class="bg-primary text-white mb-0" id="about">
  <div class="container">
    <h2 class="text-center text-uppercase text-white">About</h2>
    <hr class="star-light mb-5">
    <div class="row">
      <div class="col-lg-4 ml-auto">
        <p class="lead">New incomes and expenses can be entered with just a few clicks letting you keep an overview of your finances so you stop experiencing those nasty surprises at the end of the month.</p>
      </div>
      <div class="col-lg-4 mr-auto">
        <p class="lead">The interface is kept simple while providing you with all the features you need to plan and manage your finances. Nothing more, nothing less.</p>
      </div>
    </div>
    <% unless user_signed_in? %>
      <div class="text-center mt-4">
        <a class="app-modal-item btn btn-xl btn-outline-light" href="#logreg-forms">
          <i class="fas fa-registered mr-2"></i>
          Join Now!
        </a>
      </div>
    <% end %>
  </div>
</section>

app/views/main/_categories_modals.html.erb
<!-- Categories Modal 1 -->
<div class="app-modal mfp-hide" id="categories-modal-1">
  <div class="app-modal-dialog bg-white">
    <a class="close-button d-none d-md-block app-modal-dismiss" href="#">
      <i class="fa fa-3x fa-times"></i>
    </a>
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-10 mx-auto">
          <h3 class="text-secondary text-uppercase mb-0">Income</h3>
          <hr class="star-dark mb-5">
          <%= image_tag 'income.jpg', class: 'img-fluid mb-5', size: '400x500' %>
          <h4 class="mb-5">Create your own income categories to track how much money you get.</h4>
          <a class="btn btn-primary btn-lg rounded-pill app-modal-dismiss" href="#">
            <i class="fa fa-close"></i>
            Close</a>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Categories Modal 2 -->
<div class="app-modal mfp-hide" id="categories-modal-2">
  <div class="app-modal-dialog bg-white">
    <a class="close-button d-none d-md-block app-modal-dismiss" href="#">
      <i class="fa fa-3x fa-times"></i>
    </a>
    <div class="container text-center">
      <div class="row">
        <div class="col-lg-10 mx-auto">
          <h3 class="text-secondary text-uppercase mb-0">Expenses</h3>
          <hr class="star-dark mb-5">
          <%= image_tag 'expenses.jpg', class: 'img-fluid mb-5', size: '400x500' %>
          <h4 class="mb-5">Create your own categories to track how much money you spend.</h4>
          <a class="btn btn-primary btn-lg rounded-pill app-modal-dismiss" href="#">
            <i class="fa fa-close"></i>
            Close</a>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Alert modal -->
<div id="alert-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form>
        <div class="modal-header">
          <h4 class="modal-title">Error!</h4>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <input type="button" class="btn btn-default" data-dismiss="modal" value="OK">
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Delete Modal HTML -->
<div id="delete-category-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form>
        <div class="modal-header">
          <h4 class="modal-title">Delete Category</h4>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this Category?</p>
          <p class="text-warning">
            <small>You will also delete all money operations that are related to it!</small>
          </p>
          <input type="hidden" class="category-id">
        </div>
        <div class="modal-footer">
          <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
          <input type="button" class="btn btn-danger delete-button" value="Delete">
        </div>
      </form>
    </div>
  </div>
</div>

app/views/main/_categories_section.html.erb
<!-- Categories Grid Section -->
<section class="categories" id="categories">
  <div class="container">
    <% if user_signed_in? %>
      <h2 class="text-center text-uppercase text-secondary mb-0">Your Categories</h2>
      <hr class="star-dark mb-5">
      <div class="row">
        <div class="col-md-12 col-lg-6">
          <div class="table-wrapper">
            <div class="table-title">
              <div class="row">
                <div class="col-sm-8">
                  <h2 class="text-center text-uppercase text-secondary mb-0">Income</h2>
                </div>
                <div class="col-sm-4">
                  <button type="button" class="btn btn-info add-new" data-category-type-id="<%= CategoryType.category_type_id('Income') %>"><i class="fa fa-plus"></i> Add New</button>
                </div>
              </div>
            </div>
            <table class="table table-bordered">
              <thead>
              <tr>
                <th>Name</th>
                <th>Actions</th>
              </tr>
              </thead>
              <tbody>
              <% if @income_categories.blank? %>
                <tr class="empty">
                  <td colspan="2">No categories</td>
                </tr>
              <% else %>
                <% @income_categories.each do |income_category| %>
                  <tr>
                    <td><%= income_category[:name] %></td>
                    <td>
                      <%= hidden_field_tag :category_id, income_category[:id] %>
                      <%= hidden_field_tag :category_type_id, income_category.category_type[:id] %>
                      <a class="add" title="Add" data-toggle="tooltip"><i class="material-icons">&#xE03B;</i></a>
                      <a class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                      <a class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                    </td>
                  </tr>
                <% end %>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="col-md-12 col-lg-6">
          <div class="table-wrapper">
            <div class="table-title">
              <div class="row">
                <div class="col-sm-8">
                  <h2 class="text-center text-uppercase text-secondary mb-0">Expenses</h2>
                </div>
                <div class="col-sm-4">
                  <button type="button" class="btn btn-info add-new" data-category-type-id="<%= CategoryType.category_type_id('Expenses') %>"><i class="fa fa-plus"></i> Add New</button>
                </div>
              </div>
            </div>
            <table class="table table-bordered">
              <thead>
              <tr>
                <th>Name</th>
                <th>Actions</th>
              </tr>
              </thead>
              <tbody>
              <% if @expenses_categories.blank? %>
                <tr class="empty">
                  <td colspan="2">No categories</td>
                </tr>
              <% else %>
                <% @expenses_categories.each do |expenses_category| %>
                  <tr>
                    <td><%= expenses_category[:name] %></td>
                    <td>
                      <%= hidden_field_tag :category_id, expenses_category[:id] %>
                      <%= hidden_field_tag :category_type_id, expenses_category.category_type[:id] %>
                      <a class="add" title="Add" data-toggle="tooltip"><i class="material-icons">&#xE03B;</i></a>
                      <a class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                      <a class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                    </td>
                  </tr>
                <% end %>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% else %>
      <h2 class="text-center text-uppercase text-secondary mb-0">Categories</h2>
      <hr class="star-dark mb-5">
      <div class="row">
        <div class="col-md-12 col-lg-6">
          <a class="app-modal-item categories-item d-block mx-auto" href="#categories-modal-1">
            <div class="categories-item-caption d-flex position-absolute h-100 w-100">
              <div class="categories-item-caption-content my-auto w-100 text-center text-white">
                <i class="fas fa-search-plus fa-3x"></i>
              </div>
            </div>
            <%= image_tag 'income.jpg', class: 'img-fluid' %>
          </a>
        </div>
        <div class="col-md-12 col-lg-6">
          <a class="app-modal-item categories-item d-block mx-auto" href="#categories-modal-2">
            <div class="categories-item-caption d-flex position-absolute h-100 w-100">
              <div class="categories-item-caption-content my-auto w-100 text-center text-white">
                <i class="fas fa-search-plus fa-3x"></i>
              </div>
            </div>
            <%= image_tag 'expenses.jpg', class: 'img-fluid' %>
          </a>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/main/_main_table.html.erb
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>
      <span class="custom-checkbox">
        <input type="checkbox" id="select-all-checkboxes">
        <label for="select-all-checkboxes"></label>
      </span>
    </th>
    <th>Type</th>
    <th>Category</th>
    <th>Sum</th>
    <th>Comment</th>
    <th>Operation date</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% if @money_operations.blank? %>
    <tr class="empty">
      <td colspan="7">You don't have money operations for this period</td>
    </tr>
  <% else %>
    <% @money_operations.each do |money_operation| %>
      <tr>
        <td>
            <span class="custom-checkbox">
              <input type="checkbox" id="checkbox<%= money_operation[:id] %>" name="options[]" value="<%= money_operation[:id] %>">
              <label for="checkbox<%= money_operation[:id] %>"></label>
            </span>
        </td>
        <td><%= money_operation.category.category_type[:name] %></td>
        <td><%= money_operation.category[:name] %></td>
        <td><%= money_operation[:sum] %></td>
        <td><%= money_operation[:comment] %></td>
        <td><%= money_operation[:operation_date].to_date %></td>
        <td>
          <%= hidden_field_tag :money_operation_id, money_operation[:id] %>
          <%= hidden_field_tag :category_type_id, money_operation.category.category_type[:id] %>
          <a class="edit" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
          <a class="delete" data-toggle="modal"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
        </td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
<div class="clearfix">
  <div class="page-info">
    <%= page_entries_info @money_operations , container: false %>
  </div>
  <% if @money_operations.present? %>
    <a class="btn btn-info show-chart" data-toggle="modal">
      <span>Show pie chart</span>
    </a>
  <% end %>
  <%= will_paginate @money_operations, params: { action: 'render_main_table', controller: 'money_operation' } %>
</div>

app/views/main/_money_operations_add_modal.html.erb
<%= form_for(MoneyOperation.new, url: 'money_operation/ajax_add_money_operation', method: :post, format: :json, remote: true) do |f| %>
  <div class="modal-header">
    <h4 class="modal-title">Add Money Operation</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  </div>
  <div class="modal-body">
    <div class="form-group">
      <label>Type</label>
      <select class="form-control money_operation_category_type">
        <% CategoryType.all.each do |category_type| %>
          <option value="<%= category_type[:id] %>"><%= category_type[:name] %></option>
        <% end %>
      </select>
    </div>
    <div class="form-group">
      <label>Category</label>
      <%= f.select :category_id, grouped_options_for_select(Category.for_select(current_user)), {}, { class: "form-control" } %>
    </div>
    <div class="form-group">
      <label>Sum</label>
      <%= f.text_field :sum, id: "sum", class: "form-control" %>
    </div>
    <div class="form-group">
      <label>Comment</label>
      <%= f.text_area :comment, id: "comment", class: "form-control" %>
    </div>
    <div class="form-group">
      <label>Operation date</label>
      <%= f.text_field :operation_date, id: "operation_date", class: "form-control operation-date-input", value: Time.now.strftime('%Y-%m-%d') %>
    </div>
  </div>
  <div class="modal-footer">
    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
    <a href="#" class="btn btn-success add-new">Add</a>
  </div>
<% end %>

app/views/main/_money_operations_chart_modal.html.erb
<div class="row">
  <div class="col-md-12 col-lg-6">
    <h3 class="text-center">Income Chart:</h3>
    <%= pie_chart money_operation_income_chart_path(start_date: params[:start_date], end_date: params[:end_date]), prefix: "$", messages: { empty: "No data" }, colors: %w(#3A754E #2A8371 #318E94 #5B96B3 #9299C6 #CB98CA) %>
  </div>
  <div class="col-md-12 col-lg-6">
    <h3 class="text-center">Expenses Chart:</h3>
    <%= pie_chart money_operation_expenses_chart_path(start_date: params[:start_date], end_date: params[:end_date]), prefix: "$", messages: { empty: "No data" }, colors: %w(#3A754E #2A8371 #318E94 #5B96B3 #9299C6 #CB98CA) %>
  </div>
</div>

app/views/main/_money_operations_edit_modal.html.erb
<%= form_for(@money_operation, url: 'money_operation/ajax_edit_money_operation', method: :post, format: :json, remote: true) do |f| %>
  <div class="modal-header">
    <h4 class="modal-title">Edit Money Operation</h4>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  </div>
  <%= f.hidden_field :id %>
  <div class="modal-body">
    <div class="form-group">
      <label>Type</label>
      <select class="form-control money_operation_category_type">
        <% CategoryType.all.each do |category_type| %>
          <option value="<%= category_type[:id] %>"><%= category_type[:name] %></option>
        <% end %>
      </select>
    </div>
    <div class="form-group">
      <label>Category</label>
      <%= f.grouped_collection_select :category_id, CategoryType.all, :category, :name, :id, :name, {}, { class: "form-control" } %>
    </div>
    <div class="form-group">
      <label>Sum</label>
      <%= f.text_field :sum, id: "sum", class: "form-control" %>
    </div>
    <div class="form-group">
      <label>Comment</label>
      <%= f.text_area :comment, id: "comment", class: "form-control" %>
    </div>
    <div class="form-group">
      <label>Operation date</label>
      <%= f.text_field :operation_date, id: "operation_date", class: "form-control operation-date-input" %>
    </div>
  </div>
  <div class="modal-footer">
    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
    <a href="#" class="btn btn-success edit-button">Edit</a>
  </div>
<% end %>

app/views/main/_money_operations_section.html.erb
<!-- Header -->
<header class="masthead bg-primary text-white text-center">
  <div class="flipWrapper">
    <div class="rotate">
      <div class="container face front">
        <% if user_signed_in? %>
          <div class="button-hint">
            <div class="btn btn-info">
              Press here to start your money tracking<span class="arrow">&darr;</span>
            </div>
          </div>
          <div>
            <%= image_tag 'main.png', class: 'img-dollar img-fluid mb-5 mx-auto' %>
          </div>
        <% else %>
          <%= image_tag 'main.png', class: 'img-dollar-simple img-fluid mb-5 mx-auto' %>
        <% end %>
        <h1 class="text-uppercase mb-0">Money tracking</h1>
        <hr class="star-light">
        <h2 class="font-weight-light mb-0">
          <% if user_signed_in? && !current_user.full_name.nil? %>
            <span class="nav-link text-uppercase">Hi, <span class="font-weight-bold"><%= current_user.full_name %></span></span><br>
          <% end %>
          We will help you to save your money
        </h2>
      </div>

      <% if user_signed_in? %>
        <div class="container face back">
          <section id="main-table-section">
            <h1 class="text-uppercase mb-0">Money operations</h1><br>
            <div class="container">
              <div class="table-wrapper">
                <div class="table-title">
                  <div class="row">
                    <div class="col-sm-6">
                      <%= text_field_tag 'operation_date_start', nil, class: 'operation-date-input' %>
                      <%= image_tag 'calendar.png', class: 'calendar-img' %>
                      <%= text_field_tag 'operation_date_end', nil, class: 'operation-date-input' %>
                      <%= image_tag 'calendar.png', class: 'calendar-img' %>
                    </div>
                    <div class="col-sm-2 export">
                      Export to:<br>
                      <%= link_to 'CSV', target: :_blank, controller: :money_operation, action: :export, format: 'csv' %>
                      <%= link_to 'XLS', target: :_blank, controller: :money_operation, action: :export, format: 'xls'%>
                    </div>
                    <div class="col-sm-4">
                      <a class="btn btn-success add-new-operation" data-toggle="modal"><i class="material-icons">&#xE147;</i>
                        <span>Add New Operation</span>
                      </a>
                      <a class="btn btn-danger delete-selected" data-toggle="modal"><i class="material-icons">&#xE15C;</i>
                        <span>Delete</span>
                      </a>
                    </div>
                  </div>
                </div>
                <div id="main-table">
                  <%= render partial: 'main/main_table' %>
                </div>
              </div>
            </div>
          </section>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/main/_money_operations_table_modals.html.erb
<!-- Add Modal HTML -->
<div id="add-operation-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

<!-- Edit Modal HTML -->
<div id="edit-operation-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

<!-- Delete Modal HTML -->
<div id="delete-operation-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form>
        <div class="modal-header">
          <h4 class="modal-title">Delete Money Operation</h4>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this Operation?</p>
          <p class="text-warning">
            <small>This action cannot be undone.</small>
          </p>
          <input type="hidden" class="money-operation-id">
        </div>
        <div class="modal-footer">
          <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
          <input type="button" class="btn btn-danger delete-button" value="Delete">
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Chart Modal HTML -->
<div id="chart-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <form>
        <div class="modal-header">
          <h4 class="modal-title">Money operations per Category</h4>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <input type="button" class="btn btn-default" data-dismiss="modal" value="OK">
        </div>
      </form>
    </div>
  </div>
</div>

app/views/main/index.html.erb
<%= render partial: "main/money_operations_section" %>
<%= render partial: "main/categories_section" %>
<%= render partial: "main/about_section" %>
<%= render partial: "main/categories_modals" %>
<%= render partial: "main/money_operations_table_modals" %>