config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'main/index'

  namespace :category do
    post 'ajax_add_category'
    post 'ajax_edit_category'
    post 'ajax_delete_category'
  end

  namespace :money_operation do
    get 'export'
    get 'income_chart'
    get 'expenses_chart'
    post 'render_main_table'
    post 'render_add_modal'
    post 'render_edit_modal'
    post 'render_chart_modal'
    post 'ajax_add_money_operation'
    post 'ajax_edit_money_operation'
    post 'ajax_delete_money_operation'
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
end

app/views/layouts/modals/_change_password_form.html.erb
<%= form_for(User.new, as: :user, url: password_path(:user), html: { id: "change_password", class: "form-reset", method: :post }, remote: true) do |f| %>
  <h1 class="h3 mb-3 font-weight-normal" style="text-align: center"> Forgot your password?</h1>

  <%= render "devise/shared/error_messages", resource: User.new %>

  <div class="field">
    <%= f.email_field :email, autofocus: true, id: "change_password_email", autocomplete: "email", class: "form-control", placeholder: "Email address" %>
  </div>

  <button class="btn btn-primary btn-block" type="submit">Reset Password</button>
  <a href="#" id="cancel_reset"><i class="fas fa-angle-left"></i> Back</a>

<% end %>

app/views/layouts/modals/_edit_form.html.erb
<%= form_for(current_user, as: :user, url: registration_path(:user), html: { id: "edit_user"}, format: :json, remote: true) do |f| %>
  <h1 class="h3 mb-3 font-weight-normal text-center">Change account information</h1>

  <div class="field">
    <%= f.text_field :full_name, autofocus: true, autocomplete: "email", id: "edit_full_name", class: "form-control", placeholder: "Full name" %>
  </div>

  <div class="field">
    <%= f.email_field :email, autocomplete: "email", id: "edit_email", class: "form-control", placeholder: "Email address" %>
  </div>

  <div class="field">
    <%= f.password_field :password, autocomplete: "new-password", id: "edit_password", class: "form-control", placeholder: "Password" %>
    <% if @minimum_password_length %>
      <br/>
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.password_field :password_confirmation, autocomplete: "new-password", id: "edit_password_confirmation", class: "form-control", placeholder: "Repeat Password" %>
  </div>

  <div class="field">
    <%= f.password_field :current_password, autocomplete: "current-password", id: "edit_current_password", class: "form-control", placeholder: "Current password" %>
  </div>

  <button class="btn btn-primary btn-block" type="submit">Update</button>

  <div class="modal-errors"></div>

<% end %>

<div class="mx-auto">
  <%= button_to "Cancel my account", registration_path(:user), data: {confirm: "Are you sure?"}, method: :delete, class: "btn btn-danger btn-block" %>
</div>

app/views/layouts/modals/_login_modal.html.erb
<!-- Login Modal -->
<div class="app-modal mfp-hide" id="logreg-forms">
  <div class="app-modal-dialog bg-white">
    <a class="close-button d-none d-md-block app-modal-dismiss" href="#">
      <i class="fa fa-3x fa-times"></i>
    </a>
    <div class="container text-center">
      <div class="row">
        <% if user_signed_in? %>
          <%= render 'layouts/modals/edit_form' %>
        <% else %>
          <%= render 'layouts/modals/signin_form' %>
          <%= render 'layouts/modals/signup_form' %>
          <%= render 'layouts/modals/change_password_form' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/modals/_signin_form.html.erb
<%= form_for(User.new, url: session_path(:user), html: { id: "sign_in_user", class: "form-signin" }, format: :json, remote: true) do |f| %>
  <h1 class="h3 mb-3 font-weight-normal" style="text-align: center"> Sign in</h1>
  <div class="social-login">
    <button class="btn google-btn social-btn" type="button">
      <a href=<%= omniauth_authorize_path(:user, :google_oauth2) %>>
        <span><i class="fab fa-google-plus-g"></i>
          Sign up with Google+
        </span>
      </a>
    </button>
  </div>

  <p style="text-align:center">OR</p>

  <%= f.email_field :email, autofocus: true, autocomplete: "email", id: "signin_email", class: "form-control", placeholder: "Email address" %>
  <%= f.password_field :password, autocomplete: "current-password", id: "signin_password", class: "form-control", placeholder: "Password" %>

  <button class="btn btn-success btn-block" type="submit"><i class="fas fa-sign-in-alt"></i> Log in</button>
  <div class="modal-errors"></div>
  <a href="#" id="forgot_pswd">Forgot password?</a>
  <hr>

  <button class="btn btn-primary btn-block" type="button" id="btn-signup"><i class="fas fa-user-plus"></i> Sign up New
    Account
  </button>
<% end %>

app/views/layouts/modals/_signup_form.html.erb
<%= form_for(User.new, url: registration_path(:user), html: { id: "sign_up_user", class: "form-signup" }, remote: true) do |f| %>
  <h1 class="h3 mb-3 font-weight-normal" style="text-align: center"> Sign up</h1>

  <%= render "devise/shared/error_messages", resource: User.new %>

  <div class="social-login">
    <button class="btn google-btn social-btn" type="button">
      <a href=<%= omniauth_authorize_path(:user, :google_oauth2) %>>
        <span><i class="fab fa-google-plus-g"></i>
          Sign up with Google+
        </span>
      </a>
    </button>
  </div>

  <p style="text-align:center">OR</p>

  <div class="field">
    <%= f.text_field :full_name, autofocus: true, autocomplete: "email", id: "signup_full_name", class: "form-control", placeholder: "Full name" %>
  </div>

  <div class="field">
    <%= f.email_field :email, autocomplete: "email", id: "signup_email", class: "form-control", placeholder: "Email address" %>
  </div>

  <div class="field">
    <%= f.password_field :password, autocomplete: "new-password", id: "signup_password", class: "form-control", placeholder: "Password" %>
  </div>

  <div class="field">
    <%= f.password_field :password_confirmation, autocomplete: "new-password", id: "signup_password_confirmation", class: "form-control", placeholder: "Repeat Password" %>
  </div>

  <button class="btn btn-primary btn-block" type="submit"><i class="fas fa-user-plus"></i> Sign Up</button>
  <div class="modal-errors"></div>
  <a href="#" id="cancel_signup"><i class="fas fa-angle-left"></i> Back</a>

<% end %>